server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: accountsModule
          uri: lb://ACCOUNTS
          predicates:
            - Path=/eazybank/accounts/api/**
          filters:
            - RewritePath=/eazybank/accounts/api/(?<segment>.*), /${segment}"
        - id: loansModule
          uri: lb://LOANS
          predicates:
            - Path=/eazybank/loans/api/**
          filters:
            - RewritePath=/eazybank/loans/api/(?<segment>.*), /${segment}"
        - id: cardsModule
          uri: lb://CARDS
          predicates:
            - Path=/eazybank/cards/api/**
          filters:
            - RewritePath=/eazybank/cards/api/(?<segment>.*), /${segment}"